# global alias
alias -g L="| less"
alias -g G="| grep"
alias -g GI="| grep -ri"

# alias
alias lst="ls -ltr --color=auto"
alias l="ls -ltr --color=auto"
alias la="ls -la --color=auto"
alias ll="ls -l --color=auto"
alias so="source"
alias sozc="source $ZDOTDIR/.zshrc"
alias v="vim"
alias vi="vim"
alias vz="vim $ZDOTDIR/.zshrc"
alias c="cdr"
alias h="fc -lt '%F %T' 1"
alias cp="cp -i"
alias rm="rm -i"
alias mkdir="mkdir -p"
alias ..="c ../"
